version: '3.9'

services:
    mongo:
      container_name: ${DB_CONTAINER_NAME}
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ${MONGODB_DOCKER_VOLUME_HOST_PATH}:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    schedule:
      container_name: ${PARSER_CONTAINER_NAME}
      build: .
      ports:
        - 8083:8080
      environment:
        - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
        - PARSER_CONTAINER_NAME=${PARSER_CONTAINER_NAME}
        - MONGODB_USERNAME=${MONGODB_USERNAME}
        - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        - SERVICE_UPDATE_TIMER_SECS=${SERVICE_UPDATE_TIMER_SECS}
        - SCHEDULE_BASE_URL=${SCHEDULE_BASE_URL}
        - SCHEDULE_TEACHER_LIST_URL=${SCHEDULE_TEACHER_LIST_URL}
        - SCHEDULE_GROUP_LIST_URL=${SCHEDULE_GROUP_LIST_URL}
        - SCHEDULE_API_URL=${SCHEDULE_API_URL}
