version: '3.9'

services:
    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ${MONGODB_DOCKER_VOLUME_HOST_PATH}:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
