version: '3.9'

services:
    schedule:
      build: .
      ports:
        - 8083:8080
      environment:
        - MONGODB_USERNAME=${MONGODB_USERNAME}
        - MONGODB_PASSWORD=${MONGODB_PASSWORD}
        - SERVICE_UPDATE_TIMER_SECS=${SERVICE_UPDATE_TIMER_SECS}
        - SCHEDULE_BASE_URL=${SCHEDULE_BASE_URL}
        - SCHEDULE_TEACHER_LIST_URL=${SCHEDULE_TEACHER_LIST_URL}
        - SCHEDULE_GROUP_LIST_URL=${SCHEDULE_GROUP_LIST_URL}
        - SCHEDULE_API_URL=${SCHEDULE_API_URL}
    mongo:
      image: mongo:latest
      ports:
        - 27017:27017
      volumes:
        - ${MONGODB_DOCKER_VOLUME_HOST_PATH}:/data/db
      environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
